"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { GradientButton, PageIntro, Pill, ThemePage } from "@/components/site-chrome";

const A = "/assets/figma";
const pageCopy = "Stories & insights that spark ideas from niche updates to business tips, explore our latest blogs that are sure to spark new ideas and fuel your growth.";
const blogCards = [
  ["UX review presentation", "Olivia Rhye", "02.png"], ["Best books on scaling your startup", "Olivia Rhye", "04.png"],
  ["Building your API Stack", "Olivia Rhye", "11.png"], ["Best books on scaling your startup", "Olivia Rhye", "04.png"],
  ["PM mental models", "Olivia Rhye", "06.png"], ["What is Wireframing?", "Olivia Rhye", "08.png"],
  ["How collaboration makes us better designers", "Olivia Rhye", "02.png"], ["Our top javascrips frameworks to use", "Olivia Rhye", "08.png"],
];

function AboutPage() {
  const [tab, setTab] = useState("Our Values");
  const values = ["Innovation", "Teamwork", "Integrity", "Customer Centricity", "Excellence"];
  return <>
    <PageIntro label="About Us" title="Company Overview" copy="Agrani Technologies and Services Limited (ATSL) is a dynamic and forward-thinking IT company based in Bangladesh, committed to providing innovative solutions that solve real-world challenges." />
    <section className="about-hero container"><Image src={`${A}/about/09.jpeg`} fill sizes="1239px" alt="Agrani team collaborating" /></section>
    <section className="directors container"><div><h2>A word from the<br />Director</h2><p>Driven by integrity, innovation, and a commitment to quality, our leadership team brings decades of experience to every partnership.</p><strong>Kamrul Islam</strong><small>Managing Director (25+ yrs experience)</small></div><Image src={`${A}/about/02.jpeg`} width={360} height={410} alt="Tanvir Mosaddaque" /><div className="director-copy"><p>Tanvir Mosaddaque joins us as Executive Director of Agrani Technologies and Services Limited. His leadership and global experience continue to strengthen our vision and execution.</p><strong>Tanvir Mosaddaque</strong><small>Executive Director (25+ yrs experience)</small></div></section>
    <section className="purpose-section"><div className="container"><h2>Driven by purpose, guided by<br />Mission, vision, defined by values</h2><p>Through a commitment to innovation, integrity and excellence, we shape every solution.</p><div className="tab-row">{["Our Mission", "Our Vision", "Our Values"].map(x => <button className={tab === x ? "active" : ""} onClick={() => setTab(x)} key={x}>{x}</button>)}</div><div className="purpose-body"><Image src={`${A}/about/09.jpeg`} width={520} height={350} alt="Team building the future" /><div><h3>{tab === "Our Values" ? "Coding for a Better Future: Empowering Ideas, Inspiring Innovation" : tab}</h3>{tab === "Our Values" ? <div className="value-grid">{values.map(v => <article key={v}><span>✦</span><h4>{v}</h4><p>We embrace change and uphold the highest standards of professionalism.</p></article>)}</div> : <ul><li>Deliver innovative, scalable and sustainable technology solutions.</li><li>Bridge the digital divide through accessible and inclusive digital services.</li><li>Drive socio-economic development through technology.</li></ul>}</div></div></div></section>
  </>;
}

function CatalogPage({ products = false }: { products?: boolean }) {
  const [open, setOpen] = useState(0);
  const services = products ? ["Portfolio", "Industries Served"] : ["Software Development", "Tech Consultancy", "System Integration & Interoperability", "Comprehensive Cloud & Infrastructure Services", "Cybersecurity Solutions", "Managed ICT Services", "E-Governance Solutions", "AI-Powered Government Services", "Smart Transportation Ecosystem", "IT Training", "Offshore IT Services"];
  const details = products ? ["Revenue & Fees Collection System", "Enterprise Resource Planning System", "Management Information System", "Document Digitization System", "Transport Automation System", "Payment Gateway Solution", "Port Automation System", "Sales Process Solution", "Biometrics Solution", "Internet of Things"] : ["Enterprise Resource Planning (ERP) System", "Management Information System (MIS)", "Document Management System", "Learning Management System (LMS)", "E-commerce Platform", "Payment Integration Solution", "Multimodal biometric solutions"];
  return <><PageIntro label="Product and Services" title="Real-World Products" copy={pageCopy} /><section className="catalog container"><div className="tab-row"><Link className={!products ? "active" : ""} href="/services">Services</Link><Link className={products ? "active" : ""} href="/products">Products</Link></div><p>Agrani Technologies is backed by a team of highly skilled and experienced professionals, delivering future-ready products customized for specific requirements.</p><div className="catalog-list">{services.map((item, i) => <article className={open === i ? "open" : ""} key={item}><button onClick={() => setOpen(i)}><span>{String.fromCharCode(65 + i)}</span>{item}</button>{open === i && <div className="catalog-details">{details.map(x => <span key={x}>◉ {x}</span>)}<GradientButton href="/contact">Let&apos;s Discuss Project</GradientButton></div>}</article>)}</div></section></>;
}

function BlogGrid({ cases = false }: { cases?: boolean }) {
  return <><PageIntro label={cases ? "CaseStudies" : "Blog"} title={cases ? "Real-World Solutions" : "Recent Highlights"} copy={pageCopy} /><section className="blog-grid container">{blogCards.map(([title, author, image], i) => <Link href={cases ? "/case-study-details" : "/blog-details"} className="blog-card" key={`${title}-${i}`}><Image src={`${A}/blog/${image}`} width={590} height={330} alt="" /><small>{author}</small><h2>{cases && i === 0 ? "A Salon Booking UX review" : title}</h2><span>{cases ? "Read Casestudy" : "Read Post"} ↗</span></Link>)}</section></>;
}

function BlogDetails() {
  return <><PageIntro label="Blog Details" title="Digital payments revolution" /><article className="article-page container"><Image className="article-hero" src={`${A}/blog/04.png`} width={1238} height={620} alt="Digital payments revolution" /><aside><strong>Andrew Jonson</strong><span>Content manager</span><p>Share this post</p><div>Facebook&nbsp;&nbsp; Twitter&nbsp;&nbsp; Linkedin</div></aside><div className="article-copy"><h2>Introductions</h2><p>Artificial intelligence is transforming payment by improving fraud detection, automating risk assessment and personalizing customer experience. AI systems analyze transaction patterns in real time to flag unusual activity, helping businesses operate securely and efficiently.</p><p>Machine learning makes payment experiences faster and more intelligent while maintaining the trust customers expect.</p><Image src={`${A}/blog/06.png`} width={600} height={380} alt="Customer using digital payments" /><blockquote>Digital transformation provides a secure way to handle transactions for all users, simplifying routine tasks and making services more accessible.</blockquote><h2>Conclusion</h2><p>With smart tools, secure infrastructure and thoughtful customer experiences, modern payment platforms can create more value for everyone.</p></div></article><section className="similar container"><h2>Few more similar blog</h2><div className="blog-grid compact">{blogCards.slice(6).map(([t,a,img]) => <Link className="blog-card" href="/blog-details" key={t}><Image src={`${A}/blog/${img}`} width={590} height={330} alt="" /><small>{a}</small><h3>{t}</h3><span>Read Post ↗</span></Link>)}</div></section></>;
}

function CaseStudyDetails() {
  return <><PageIntro label="Project Overview" title={<>Finding and booking<br />salon services shouldn&apos;t be stressful</>} copy="Stylii makes it seamless for both customers and salon owners." /><section className="case-story container"><div className="case-lead"><h2>Problem &amp;<br />Solutions</h2><p>In today&apos;s fast-moving beauty industry, customers face delays and confusion during salon booking while many owners still rely on manual record-keeping and phone calls.</p></div><div className="problem-flow"><article><b>Problem</b><p>Manual booking and service management cause missed appointments, long wait times and frustrated clients.</p></article><article><b>Solution 01</b><p>Clients book easily while staff manage appointments and availability in one place.</p></article><article><b>Solution 02</b><p>Clear tracking improves service quality and customer satisfaction.</p></article></div></section><section className="research-section"><div className="container"><h2>Researching User To<br />Validate design Choices</h2><div className="research-stats">{[["80%", "Effortless booking flow"], ["65%", "Clear service details"], ["47%", "Helpful stylist selection"]].map(([n,l]) => <article key={n}><strong>{n}</strong><span>{l}</span></article>)}</div><Image src={`${A}/blog/02.png`} width={520} height={350} alt="User research" /></div></section><section className="case-finale container"><div className="case-mockups"><span /><span /><span /></div><div><Image src={`${A}/blog/02.png`} width={430} height={300} alt="Final solution" /><h2>From Vision to Final Execution</h2><p>With Stylii, insights turn into an adaptive salon experience that empowers customers and helps owners grow.</p></div><h2>THANKS<br /><small>For Scrolling Along</small></h2></section></>;
}

const testimonials = ["Mashreef Ahamed", "Zinia Sultana", "Jehana Mowla", "Adam Gwadar"];
function TestimonialsPage() { return <><PageIntro label="Customer Experience" title="More critics from our clients" copy={pageCopy} /><section className="testimonials container">{[...Array(3)].flatMap(() => testimonials).map((name, i) => <article key={`${name}-${i}`}><div><span className="avatar">{name[0]}</span><strong>{name}</strong><b>★★★★★</b></div><p>Working at Agrani has been an incredible experience, marked by an innovative work culture and a supportive team that inspires growth.</p><small>Executive <i>Finance &amp; Admin</i></small></article>)}</section></>; }

function ExpertisePage() {
  const team = ["Software Engineers", "System Architects", "Database Experts", "UI/UX Designer", "QA & Test Engineers", "Security Experts", "Business Analysts", "Project Managers", "Support Engineers"];
  return <><PageIntro label="Our Expertise" title="Real-World Solutions" copy={pageCopy} /><section className="expertise container"><h2>Technical Team</h2><p>Agrani&apos;s greatest asset is its people. The company employs over 100 professionals including:</p><div className="feature-grid">{team.map((x,i) => <article key={x}><div className="round-icon"><Image src={`${A}/light/raw-${String((i%4)+1).padStart(2,"0")}.png`} width={32} height={32} alt="" /></div><h3>{x}</h3><p>We build custom web and mobile applications, platforms, and future-ready systems.</p><small>Details Full Stack</small></article>)}</div><h2>Technological Expertise</h2><div className="technology-grid">{["Language", "Frameworks", "Database", "Cloud", "DevOps", "Security", "Others"].map(x => <article key={x}><h3>{x}</h3><div><span>Java</span><span>Python</span><span>React</span><span>AWS</span></div></article>)}</div><div className="csr"><h2>Our Infrastructure &amp; Facilities, Security &amp; Compliance, Partnership &amp; Affiliations, Corporate Social Responsibility</h2><div>{["Infrastructure & Facilities", "Security & Compliance", "Partnership Affiliations", "Corporate Social Responsibility (CSR)"].map(x => <button key={x}>{x}<span>⌄</span></button>)}</div></div></section></>;
}

function WhyPage() { const cards = ["12+ years experience", "100+ Professionals", "24/7 Support available", "Highly Experienced and Professionals", "Maintain Security", "Cost Efficient Product and Services", "Cloud Infrastructure", "High-Quality Product", "Deliver On-time"]; return <><PageIntro label="Why Choose Us" title="Real-World Solutions" copy={pageCopy} /><section className="why-cards container">{cards.map((x,i) => <article className={i === 2 ? "accent" : ""} key={x}><div className="round-icon">✦</div><h2>{x}</h2><p>We build custom web and mobile applications, ERP systems, e-commerce platforms, and more, tailored to your specific business needs.</p>{i === 2 && <GradientButton>Contact Us</GradientButton>}</article>)}</section></>; }

function CareerPage() { const jobs=["Artist/Designer", "UI/UX Designer", "PHP Developer", "Full-Stack Developer"]; return <><PageIntro label="Career" title="Where technology meets opportunity" copy="Through our comprehensive training, recruitment practices and vibrant work environment, Agrani empowers talent to build meaningful careers." /><section className="career-hero container"><Image src={`${A}/career/05.jpeg`} fill sizes="1239px" alt="Agrani career opportunity" /></section><section className="employee-section"><div className="container"><h2>Employees Feedback</h2><p>Through our comprehensive training and team culture, employees gain valuable skills and build meaningful careers.</p><div className="testimonials small">{testimonials.map((x,i)=><article key={x}><strong>{x}</strong><b>★★★★★</b><p>{i%2 ? "An inspiring and supportive work environment — truly a great place to grow!" : "The calendar app has been a lifesaver! I used to forget important events, but now I'm always on top of my schedule."}</p></article>)}</div></div></section><section className="jobs container"><h2>Current Openings</h2><div className="job-grid">{jobs.map(x=><article key={x}><small>Opening</small><h3>{x}</h3><div><span>Design</span><span>Fulltime</span><span>Entry Level</span></div><strong>25,000 - 60,000 <i>BDT/Month</i></strong><GradientButton href="/contact">Apply Here</GradientButton></article>)}</div><h2>Internship Openings</h2><div className="job-grid">{jobs.map(x=><article key={x}><small>Opening</small><h3>{x}</h3><div><span>Design</span><span>Ontime</span><span>Entry Level</span></div><strong>5,000 - 10,000 <i>BDT/Month</i></strong><GradientButton href="/contact">Apply Here</GradientButton></article>)}</div></section></>; }

function ContactPage() { const info=[["Address","Plot-174/176, Road-02, Avenue-01, Mirpur DOHS, Dhaka-1216, Bangladesh"],["Phone","+880-9610944449"],["Email","info@agranitechbd.com"],["Website","www.agranitechbd.com"]]; return <><PageIntro label="Contact Us" title={<>Need expert guidance? Reach out to<br />our team—we&apos;d love to hear from you</>} copy="Through a comprehensive range of services, our experts are ready to help." /><section className="map container"><Image src={`${A}/contact/03.png`} fill sizes="1239px" alt="Agrani Technologies office location map" /></section><section className="info-grid container">{info.map(([x,y],i)=><article key={x}><div className="round-icon">{["⌂","☎","✉","⊕"][i]}</div><h3>{x}</h3><p>{y}</p></article>)}</section></>; }

export default function RoutedPage() {
  const { slug } = useParams<{ slug: string }>();
  const map: Record<string, [React.ReactNode, string]> = {
    about: [<AboutPage key="about" />, "About Us"], services: [<CatalogPage key="services" />, "Product and Services"], products: [<CatalogPage products key="products" />, "Product and Services"], blog: [<BlogGrid key="blog" />, "Others"], "blog-details": [<BlogDetails key="blog-details" />, "Others"], "case-studies": [<BlogGrid cases key="cases" />, "Others"], "case-study-details": [<CaseStudyDetails key="case" />, "Others"], "customer-experience": [<TestimonialsPage key="customers" />, "Others"], expertise: [<ExpertisePage key="expertise" />, "Others"], "why-choose-us": [<WhyPage key="why" />, "Others"], career: [<CareerPage key="career" />, "Career"], contact: [<ContactPage key="contact" />, "Contact Us"],
  };
  const selected = map[slug] || [<PageIntro key="missing" label="Agrani" title="Page not found" />, ""];
  return <ThemePage active={selected[1]}>{selected[0]}</ThemePage>;
}
